workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 45
    instance_type: mac_mini_m2
    environment:
      node: 20
      java: 17
    scripts:
      - name: Instalar dependencias
        script: |
          npm install
      - name: Generar proyecto Android
        script: |
          npx expo prebuild --platform android
      - name: Generar APK de Android
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk